<a href="https://colab.research.google.com/github/matheusschittini/analise_mercado_trabalho/blob/main/analise_mercado_trabalho.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd

import numpy as np

In [27]:
# leitura do dataset
df = pd.read_csv("dataset_trabalho.csv")
df.head(10)

,id,idade,salario,anos_experiencia,nivel_educacao,horas_trabalhadas_semana,area
0,1,56,7589.66,23,medio,47,TI
1,2,69,3129.58,21,pos,54,TI
2,3,46,3609.64,20,medio,56,educacao
3,4,32,5818.08,29,medio,57,saude
4,5,60,3843.61,3,superior,40,comercio
5,6,25,2194.31,28,pos,24,saude
6,7,78,3910.36,39,superior,59,TI
7,8,38,4345.78,37,fundamental,39,educacao
8,9,56,3089.97,10,superior,56,TI
9,10,75,4454.34,39,medio,31,TI

In [29]:
# sumário de características do meu dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        50000 non-null  int64
 1   idade                     50000 non-null  int64
 2   salario                   50000 non-null  float64
 3   anos_experiencia          50000 non-null  int64
 4   nivel_educacao            50000 non-null  object
 5   horas_trabalhadas_semana  50000 non-null  int64
 6   area                      50000 non-null  object
dtypes: float64(1), int64(4), object(2)
memory usage: 2.7+ MB

In [35]:
# estatísticas básicas
cols_numericas = [
    "idade",
    "salario",
    "anos_experiencia",
    "horas_trabalhadas_semana"
]

df[cols_numericas].agg([
    "mean",
    "std",
    "min",
    "median",
    "max"
])

            idade      salario  anos_experiencia  horas_trabalhadas_semana
mean    48.538820  3518.596727         19.416620                 39.492120
std     17.879704  1170.907055         11.532822                 11.564891
min     18.000000  1200.000000          0.000000                 20.000000
median  48.000000  3505.145000         19.000000                 40.000000
max     79.000000  8658.630000         39.000000                 59.000000

O meu dataset